const listings = [
  {
    id: 1,
    name: "Room Self Contain",
    location: "Ilorin",
    bedroom: 2,
    bathroom: 2,
    kitchen: true,
    type: "Self Contain",
    price: 60000,
    rating: 3,
    imgUrl: "public/images/card-img.png",
  },
  {
    id: 2,
    name: "1 Room Apartment",
    location: "Lagos",
    bedroom: 1,
    bathroom: 1,
    kitchen: true,
    type: "One Room",
    price: 80000,
    rating: 4,
    imgUrl: "public/images/card-img.png",
  },
  {
    id: 3,
    name: "3 Bedroom Apartment",
    location: "Abuja",
    bedroom: 2,
    bathroom: 2,
    kitchen: true,
    type: "Apartment",
    price: 120000,
    rating: 1,
    imgUrl: "public/images/card-img.png",
  },
  {
    id: 4,
    name: "Room Self Contain",
    location: "Ekiti",
    bedroom: 2,
    bathroom: 2,
    kitchen: true,
    type: "Self Contain",
    price: 60000,
    rating: 3,
    imgUrl: "public/images/card-img.png",
  },
  {
    id: 5,
    name: "1 Room Self Contain",
    location: "Ibadan",
    bedroom: 0,
    bathroom: 1,
    kitchen: true,
    type: "Self Contain",
    price: 30000,
    rating: 2,
    imgUrl: "public/images/card-img.png",
  },
  {
    id: 6,
    name: "3 Bedroom Flat",
    location: "Osogbo",
    bedroom: 3,
    bathroom: 4,
    kitchen: true,
    type: "Apartment",
    price: 30000,
    rating: 2,
    imgUrl: "public/images/card-img.png",
  },
];

export {listings}